spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book-nest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration
  security:
    noAuthUrls:
      - /v1/login
      - /v1/users
      - /v1/users/**
