ALTER TABLE Users AUTO_INCREMENT = 10001;

ALTER TABLE Users MODIFY COLUMN role ENUM('ADMIN', 'LIBRARIAN', 'MEMBER') NOT NULL;

ALTER TABLE Users MODIFY COLUMN membership_tier ENUM('REGULAR', 'PREMIUM') DEFAULT 'REGULAR';
